version: '3.9'

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=jobs
    networks:
      - merger-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: /backend/.
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    networks:
      merger-network:
        aliases:
          - backend

  frontend:
    build: /frontend/merger/.
    ports: 
      - "4200:80"
    networks:
      - merger-network
    depends_on:
      - backend

networks:
  merger-network:
    driver: bridge